### PR TITLE
Be compatible wit the aliyun-sdk 0.7.0

### PR DESCRIPTION
**Pull request by qwlong**
Be compatible wit the aliyun-sdk 0.7.0

### CODE REVIEW

**Comment by huacnlee** [comment]
说明一下兼容的原因，解决什么问题

**Comment by qwlong** [comment]
@huacnlee 

The gem invokes the object_url like:
`img_client.object_url([path, thumb].join(""), expiry: 15.minutes)`


aliyun-sdk <= 0.6.0
The object_url method is 
`def object_url(key, sign = true, expiry = 60)`

https://github.com/aliyun/aliyun-oss-ruby-sdk/blob/0.6.0/lib/aliyun/oss/bucket.rb#L593

aliyun-sdk >= 0.7.0

The object_url method is 
`def object_url(key, sign = true, expiry = 60, parameters = {})`
https://github.com/aliyun/aliyun-oss-ruby-sdk/blob/v0.7.1/lib/aliyun/oss/bucket.rb#L594

> 说明一下兼容的原因，解决什么问题

**Comment by huacnlee** [comment]
为何不升级 0.7.0?

**Comment by qwlong** [comment]
是升级了 0.7.0，有这个问题

**Pull request merged**
